name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Deploying to host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/snake-canvas/
            git pull
            npm prune
            npm install
            npm run build
            sudo systemctl stop nginx
            sudo rm -r /var/www/localghost.lt/html/*
            sudo cp -R dist /var/www/localghost.lt/html
            sudo systemctl start nginx
